cask_args appdir: '/Applications'

tap 'homebrew/bundle'

# Tip: Populate current installed brews on this file from shell:
# $ brew list -1 | noglob awk '{print "brew '\''" $0 "'\''"}' >> Brewfile
brew 'ack'
brew 'autoconf'
brew 'coreutils'
brew 'ffmpeg'
brew 'grc'
brew 'groovy'
brew 'imagemagick'
brew 'jq'
brew 'maven'
brew 'memcached'
brew 'mercurial'
brew 'mysql'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'pcre'
brew 'pkg-config'
brew 'ponysay'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ruby'
brew 'ruby-build'
brew 'siege'
brew 'spark'
brew 'tcpflow'
brew 'tmux'
brew 'vim'
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'youtube-dl'

cask 'iterm2'
cask 'google-chrome'
cask 'spectacle'
cask 'seil'
cask 'time-out'
# Need an older version, installing manually
#cask 'virtualbox'
cask 'vagrant'
cask 'firefox'
cask 'hipchat'
cask 'phpstorm'
cask 'intellij-idea-ce'
cask 'soapui'
cask 'spotify'
cask 'java'
cask 'java7'
cask 'skype'
# Missing: Monosnap
